name: Auto Build & Release APK

on:
  push:
    branches:
      - main
      - principal
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.3.1'

      - name: Prepare environment (Keystore & Env)
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          echo "MIIKZgIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFMYwZ+uC6u1rZMMM5YqB77fqwtSNAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ30YFDyf9uyoutfSPOUOUvgSCBNAIJeIlV1kypth2ch6+TUPEBhXInMDb4Do3eafVUwjFgY7SP41kWfAIa3h2B7wlDh0NMKmxvohqwsyrkmGwvmjAEkYiZUsvgqWUQZsPUALO4/pU8kDbNVxSyrRElb5fte9jm28non5n1wgnA/amfYP8aXly8tV+l3ElaAIoBjwIsDmgE3Y7meChNzMVAJS392NE8OBj7dKnUXeI/1KVhBJkuFamLrFRk5JlnlGXfp7+42IsiM+8eJOlBpfMANVYN0CjPW2V6vDo8eatmPIlwqNrkcY8X9chzLpKbS4/Bu+3dTeu+Bk3xv3Mitnnv4r4N+UViuE8U7cQHbZv5LFksiwY7EODxA3ptKzYBENzZemsiAynv6lGvo5yuv+ME3NKL8WwqzCBt+gMX/EtYzcd2WbDtTuWu3jxnHIwGC2P1zUDLOA/q0tjJge/rLHmP1Ov1qEBUTBrnE+M1MPMGOSTlzpoVKiEM0ehV8MTustVHiu2PtQA79b/HyWafhigG4UptK2e4Qibor28AY880Pf+BYNyGRXyUpiFKrpdJmUhmH3rvrycqO0UWO27qH8emrVVaTfAWDF0Il7BmsnJnAhx2vEqTRAsKCvL9ZGkkF95ErqyO31X5KtbyRyNlFpz7QVLxR9v0L5eDYY+b5DLQw+WTQPQvYoNpSKBXyyW4FeM/ZTy0pjJHXKBVsiqUiSLoP+YZ2dwpqULC0MRildL89yni4Xdpdh5RzmRKtF7nxpONV26OgUB7XxNQn3pqsSkCWKRalHk1VYEmx5fhHTlwSmjlRwpOlFVy9USHmj/ttVQvkuegYsAB4MLtfGHHCECtqodSZLsoMqjXDd0NKi7j6IX5Klfs7MjV3eHzoPMksk3BM8VdQmDiDCKY+CBt7wpywh3omzFxL64AD6OK+lL+VIOwcYqrUiMDTUZ7ZKNwvElOjkZOLXlECMHbf8J4CR5soFdbPtCaZOZBda5vrBFm3A6UjDylbtYw3bkq8JVS/KcEwV8gbA0gAG9gH/32TNP47JzwOGHfpS+9goT2bWVq7luF/Y3iss2yAUHQ2ykdA3gMFtJrjwsWRoCadRCoamAJss017bjP6/zZ917+5SiiYyF3BN/g9uKEDfEQKC6tMPNfZOAA1PLH6kbprA7x+tvsk6nw6Wp41MU7Y2tpQI9nNPDCFvS8r3nBPewdqNB1IO0sIrq1a/ZaLgk0aEop8cvU96nkkZuWclovtVtar76YtiDk4AhZfR3XsQ+GC28HxaB2k07XOw5rRrlAs5p8zfiQjZaAY8Ho5JF2j+UsmIu/wENXN3y/0ikEVXmpWQ5f2YfGH30fTZLO17W7jkX8oo62dqh6UHT8+EEhEm6gOqBKm1HaPbySp1j2E+Gy58x7aZXoKaMsuXKPyhg2iQQ5b1eLd8J7lHp9ZYQsIErgsIAMHm5iiulrFIsUkt5kukURZTutCCK1v8jzKynHG0UYEEiKwG6PF9qIVVuinR5JmnxZIHKrVGHVYJd9C/cg3a0DVlUEuL5RmGbgyJh2i5SgQlY4yJO+hgJ8vZQYclbJPNZkEV3M6Ve538wjZKmR7TPJOKAHOo7j6jMXP4JnFbLNRwxm5yp3bag9YbeB8x8Rpa1U8QsFHPT0iePApyylzamuVJQjhmWHjFSMC0GCSqGSIb3DQEJFDEgHh4AYQBuAGQAcgBvAGkAZABkAGUAYgB1AGcAawBlAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc4Nzg4NjkwNTY1NjCCBDEGCSqGSIb3DQEHBqCCBCIwggQeAgEAMIIEFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBT2pTBCB8FEKsoCuu0AM8Jnis5mOQICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEM1dPWgUwPxaeZod+QUsUAeAggOgbW6+ZjoI4HNqLyEl/BrsULYwWaXfKNq9HT4QqPOxFkmQEyiQgDjx2u57v27AMV+WoihbCkd/5TALLO0loH5KOC6aUazVHV+QifeZcjnKwPNTjif0WET8zdpnhledawziYXi1JaUrQlJFHWLC2PrHRkbXlFXoJQXl3HKdAApL7XQqZlgcxzYctJb9RpO/hu/aReudBZC38Yh6jCGBIO//g0TiRHoeCyak4OpKBy/OieCY/vRUY3xgsVAjks4l/WlM+3BX04dL6XQQaj2PpyhpGVDqWKyTtHGQcEhDXecI2TNofY5GK5glWrgfatCilo3OwagxyHZ1PHVYaf6T+v0JGhBE6r1hzOkDGsbyLXmpnWQ2OdDsE5D3mPfs9GRlx5emlLuFZr9cWLYR50dQB2Yf9bAHeodf8SGaD6fkOeC34sG3QmLSA+gpTB9QbSlR3uRW/cPU6NoG/Twu63TcyRVk1acIzWyfORFFwslhZF5rpDoa/FiGAUOgGoxJLqp7uXjUYMZz7MaXAWrq+zYWaFVCzivXC+Up7q3BmsSazWiai9/juEkFNztW0aKAEjgtnqzuq3evSNySQy1Kgj6Xi+lNPS9oH4W6RuBTi7oiU52Xk+1E26te108Gjkb7krIhQDVE7nKstPDfReGXd5Qx2FsOCeDb9wGBEH6Ww3Viq/bPiPvQY42qV+l5D8Z31xPAnbSt0riSOZY+MfaA3c/8NPQp1G/laUyBbVPL9xNENwg04oHGOtaGfKuWD0+BYiJKMwGoJu24vPAezA8YM5RP0R8ScQSKdbRBHbcDy6A2u0CvD51T2COAUyVdcKIk1ohs6qEHpoSvN8DEh7sB+b/+q+dc9H4BUi3djvZvmfYsZrL/vixY+FYD6yTUhCqw2l5YAe71SAi2ItJsfIytE0XDoZz1g9lWoY9nSK9gIZubKTkL6oXlZGaD9Kaew2/gc5I0rxfYPwkEwUbGKnGnQMlS0Lr/WIBW2SAWzU3tiakfx5oCz8JPA9xanm6+bQVOxDbh6pjeq4TOVzK3V5zEwQsY542lCqQDnNXJWZtOn9SHbPrqjC3VqjDabV0cW5WdxIxekFJS/geRLQwsIWNSJUJfsy6uLYUeBq11iid8ZmpFqn1HLiqKpDtTgyoOV3MmEzQXSSqYUcc0LF9yoZn3CETFEQH+1d0eg0pwVeT31ukZLPrUR9BY6l1hotRqtVeQXZM1wgdwokQuS+nTxpChlTsdnexZ/zBNMDEwDQYJYIZIAWUDBAIBBQAEIGDoAS2SDNX0Oe4t+WaQJxDitLa8BmQJLfD8mwlTlCixBBT9tYWPoHCHNPDJ1pc19aKrnRTMnwICJxA=" | base64 -d > debug.keystore
          touch .env
          if [ -f .env.example ]; then cp .env.example .env; fi

      - name: Generate Version Tag
        id: version_tag
        run: echo "tag=v$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Build Debug APK
        run: gradle assembleDebug -PversionCode=${{ github.run_number }} -PversionName="${{ steps.version_tag.outputs.tag }}" --no-daemon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_tag.outputs.tag }}
          name: Actualización Automática ${{ steps.version_tag.outputs.tag }}
          body: "Esta actualización fue generada automáticamente por GitHub Actions."
          files: app/build/outputs/apk/debug/app-debug.apk
